package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BIAOQIAN.
 */
public class biaoqian {

    private Long biaoqianid;
    private String biaoqiancode;
    private String biaoqianleibie;
    private String jingdu;
    private String weidu;

    public biaoqian() {
    }

    public biaoqian(Long biaoqianid) {
        this.biaoqianid = biaoqianid;
    }

    public biaoqian(Long biaoqianid, String biaoqiancode, String biaoqianleibie, String jingdu, String weidu) {
        this.biaoqianid = biaoqianid;
        this.biaoqiancode = biaoqiancode;
        this.biaoqianleibie = biaoqianleibie;
        this.jingdu = jingdu;
        this.weidu = weidu;
    }

    public Long getBiaoqianid() {
        return biaoqianid;
    }

    public void setBiaoqianid(Long biaoqianid) {
        this.biaoqianid = biaoqianid;
    }

    public String getBiaoqiancode() {
        return biaoqiancode;
    }

    public void setBiaoqiancode(String biaoqiancode) {
        this.biaoqiancode = biaoqiancode;
    }

    public String getBiaoqianleibie() {
        return biaoqianleibie;
    }

    public void setBiaoqianleibie(String biaoqianleibie) {
        this.biaoqianleibie = biaoqianleibie;
    }

    public String getJingdu() {
        return jingdu;
    }

    public void setJingdu(String jingdu) {
        this.jingdu = jingdu;
    }

    public String getWeidu() {
        return weidu;
    }

    public void setWeidu(String weidu) {
        this.weidu = weidu;
    }

}
