package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BUMEN.
 */
public class bumen {

    private Long bumenid;
    private Integer fujiid;
    private String bumenname;
    private String miaoshu;

    public bumen() {
    }

    public bumen(Long bumenid) {
        this.bumenid = bumenid;
    }

    public bumen(Long bumenid, Integer fujiid, String bumenname, String miaoshu) {
        this.bumenid = bumenid;
        this.fujiid = fujiid;
        this.bumenname = bumenname;
        this.miaoshu = miaoshu;
    }

    public Long getBumenid() {
        return bumenid;
    }

    public void setBumenid(Long bumenid) {
        this.bumenid = bumenid;
    }

    public Integer getFujiid() {
        return fujiid;
    }

    public void setFujiid(Integer fujiid) {
        this.fujiid = fujiid;
    }

    public String getBumenname() {
        return bumenname;
    }

    public void setBumenname(String bumenname) {
        this.bumenname = bumenname;
    }

    public String getMiaoshu() {
        return miaoshu;
    }

    public void setMiaoshu(String miaoshu) {
        this.miaoshu = miaoshu;
    }

}
