package com.intelligent.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.intelligent.greendao.biaoqian;
import com.intelligent.greendao.bumen;
import com.intelligent.greendao.gdlx;
import com.intelligent.greendao.guandian;
import com.intelligent.greendao.guanxian;
import com.intelligent.greendao.gxlb;
import com.intelligent.greendao.jlx;
import com.intelligent.greendao.shuxing;
import com.intelligent.greendao.user;
import com.intelligent.greendao.xuncha;
import com.intelligent.greendao.guzhangshenbao;
import com.intelligent.greendao.dianli;

import com.intelligent.greendao.biaoqianDao;
import com.intelligent.greendao.bumenDao;
import com.intelligent.greendao.gdlxDao;
import com.intelligent.greendao.guandianDao;
import com.intelligent.greendao.guanxianDao;
import com.intelligent.greendao.gxlbDao;
import com.intelligent.greendao.jlxDao;
import com.intelligent.greendao.shuxingDao;
import com.intelligent.greendao.userDao;
import com.intelligent.greendao.xunchaDao;
import com.intelligent.greendao.guzhangshenbaoDao;
import com.intelligent.greendao.dianliDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig biaoqianDaoConfig;
    private final DaoConfig bumenDaoConfig;
    private final DaoConfig gdlxDaoConfig;
    private final DaoConfig guandianDaoConfig;
    private final DaoConfig guanxianDaoConfig;
    private final DaoConfig gxlbDaoConfig;
    private final DaoConfig jlxDaoConfig;
    private final DaoConfig shuxingDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig xunchaDaoConfig;
    private final DaoConfig guzhangshenbaoDaoConfig;
    private final DaoConfig dianliDaoConfig;

    private final biaoqianDao biaoqianDao;
    private final bumenDao bumenDao;
    private final gdlxDao gdlxDao;
    private final guandianDao guandianDao;
    private final guanxianDao guanxianDao;
    private final gxlbDao gxlbDao;
    private final jlxDao jlxDao;
    private final shuxingDao shuxingDao;
    private final userDao userDao;
    private final xunchaDao xunchaDao;
    private final guzhangshenbaoDao guzhangshenbaoDao;
    private final dianliDao dianliDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        biaoqianDaoConfig = daoConfigMap.get(biaoqianDao.class).clone();
        biaoqianDaoConfig.initIdentityScope(type);

        bumenDaoConfig = daoConfigMap.get(bumenDao.class).clone();
        bumenDaoConfig.initIdentityScope(type);

        gdlxDaoConfig = daoConfigMap.get(gdlxDao.class).clone();
        gdlxDaoConfig.initIdentityScope(type);

        guandianDaoConfig = daoConfigMap.get(guandianDao.class).clone();
        guandianDaoConfig.initIdentityScope(type);

        guanxianDaoConfig = daoConfigMap.get(guanxianDao.class).clone();
        guanxianDaoConfig.initIdentityScope(type);

        gxlbDaoConfig = daoConfigMap.get(gxlbDao.class).clone();
        gxlbDaoConfig.initIdentityScope(type);

        jlxDaoConfig = daoConfigMap.get(jlxDao.class).clone();
        jlxDaoConfig.initIdentityScope(type);

        shuxingDaoConfig = daoConfigMap.get(shuxingDao.class).clone();
        shuxingDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        xunchaDaoConfig = daoConfigMap.get(xunchaDao.class).clone();
        xunchaDaoConfig.initIdentityScope(type);

        guzhangshenbaoDaoConfig = daoConfigMap.get(guzhangshenbaoDao.class).clone();
        guzhangshenbaoDaoConfig.initIdentityScope(type);

        dianliDaoConfig = daoConfigMap.get(dianliDao.class).clone();
        dianliDaoConfig.initIdentityScope(type);

        biaoqianDao = new biaoqianDao(biaoqianDaoConfig, this);
        bumenDao = new bumenDao(bumenDaoConfig, this);
        gdlxDao = new gdlxDao(gdlxDaoConfig, this);
        guandianDao = new guandianDao(guandianDaoConfig, this);
        guanxianDao = new guanxianDao(guanxianDaoConfig, this);
        gxlbDao = new gxlbDao(gxlbDaoConfig, this);
        jlxDao = new jlxDao(jlxDaoConfig, this);
        shuxingDao = new shuxingDao(shuxingDaoConfig, this);
        userDao = new userDao(userDaoConfig, this);
        xunchaDao = new xunchaDao(xunchaDaoConfig, this);
        guzhangshenbaoDao = new guzhangshenbaoDao(guzhangshenbaoDaoConfig, this);
        dianliDao = new dianliDao(dianliDaoConfig, this);

        registerDao(biaoqian.class, biaoqianDao);
        registerDao(bumen.class, bumenDao);
        registerDao(gdlx.class, gdlxDao);
        registerDao(guandian.class, guandianDao);
        registerDao(guanxian.class, guanxianDao);
        registerDao(gxlb.class, gxlbDao);
        registerDao(jlx.class, jlxDao);
        registerDao(shuxing.class, shuxingDao);
        registerDao(user.class, userDao);
        registerDao(xuncha.class, xunchaDao);
        registerDao(guzhangshenbao.class, guzhangshenbaoDao);
        registerDao(dianli.class, dianliDao);
    }
    
    public void clear() {
        biaoqianDaoConfig.getIdentityScope().clear();
        bumenDaoConfig.getIdentityScope().clear();
        gdlxDaoConfig.getIdentityScope().clear();
        guandianDaoConfig.getIdentityScope().clear();
        guanxianDaoConfig.getIdentityScope().clear();
        gxlbDaoConfig.getIdentityScope().clear();
        jlxDaoConfig.getIdentityScope().clear();
        shuxingDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        xunchaDaoConfig.getIdentityScope().clear();
        guzhangshenbaoDaoConfig.getIdentityScope().clear();
        dianliDaoConfig.getIdentityScope().clear();
    }

    public biaoqianDao getBiaoqianDao() {
        return biaoqianDao;
    }

    public bumenDao getBumenDao() {
        return bumenDao;
    }

    public gdlxDao getGdlxDao() {
        return gdlxDao;
    }

    public guandianDao getGuandianDao() {
        return guandianDao;
    }

    public guanxianDao getGuanxianDao() {
        return guanxianDao;
    }

    public gxlbDao getGxlbDao() {
        return gxlbDao;
    }

    public jlxDao getJlxDao() {
        return jlxDao;
    }

    public shuxingDao getShuxingDao() {
        return shuxingDao;
    }

    public userDao getUserDao() {
        return userDao;
    }

    public xunchaDao getXunchaDao() {
        return xunchaDao;
    }

    public guzhangshenbaoDao getGuzhangshenbaoDao() {
        return guzhangshenbaoDao;
    }

    public dianliDao getDianliDao() {
        return dianliDao;
    }

}
