package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIANLI.
 */
public class dianli {

    private Long dianlicode;
    private String zhanming;
    private String luming;
    private String tiaoxuhao;
    private String changdu;
    private String qidian;
    private String zhongdian;
    private String xinghao;
    private String fadianshijian;
    private String jingdu;
    private String weidu;
    private String biaoqiancode;
    private String bangdingshijian;
    private String beizhu;

    public dianli() {
    }

    public dianli(Long dianlicode) {
        this.dianlicode = dianlicode;
    }

    public dianli(Long dianlicode, String zhanming, String luming, String tiaoxuhao, String changdu, String qidian, String zhongdian, String xinghao, String fadianshijian, String jingdu, String weidu, String biaoqiancode, String bangdingshijian, String beizhu) {
        this.dianlicode = dianlicode;
        this.zhanming = zhanming;
        this.luming = luming;
        this.tiaoxuhao = tiaoxuhao;
        this.changdu = changdu;
        this.qidian = qidian;
        this.zhongdian = zhongdian;
        this.xinghao = xinghao;
        this.fadianshijian = fadianshijian;
        this.jingdu = jingdu;
        this.weidu = weidu;
        this.biaoqiancode = biaoqiancode;
        this.bangdingshijian = bangdingshijian;
        this.beizhu = beizhu;
    }

    public Long getDianlicode() {
        return dianlicode;
    }

    public void setDianlicode(Long dianlicode) {
        this.dianlicode = dianlicode;
    }

    public String getZhanming() {
        return zhanming;
    }

    public void setZhanming(String zhanming) {
        this.zhanming = zhanming;
    }

    public String getLuming() {
        return luming;
    }

    public void setLuming(String luming) {
        this.luming = luming;
    }

    public String getTiaoxuhao() {
        return tiaoxuhao;
    }

    public void setTiaoxuhao(String tiaoxuhao) {
        this.tiaoxuhao = tiaoxuhao;
    }

    public String getChangdu() {
        return changdu;
    }

    public void setChangdu(String changdu) {
        this.changdu = changdu;
    }

    public String getQidian() {
        return qidian;
    }

    public void setQidian(String qidian) {
        this.qidian = qidian;
    }

    public String getZhongdian() {
        return zhongdian;
    }

    public void setZhongdian(String zhongdian) {
        this.zhongdian = zhongdian;
    }

    public String getXinghao() {
        return xinghao;
    }

    public void setXinghao(String xinghao) {
        this.xinghao = xinghao;
    }

    public String getFadianshijian() {
        return fadianshijian;
    }

    public void setFadianshijian(String fadianshijian) {
        this.fadianshijian = fadianshijian;
    }

    public String getJingdu() {
        return jingdu;
    }

    public void setJingdu(String jingdu) {
        this.jingdu = jingdu;
    }

    public String getWeidu() {
        return weidu;
    }

    public void setWeidu(String weidu) {
        this.weidu = weidu;
    }

    public String getBiaoqiancode() {
        return biaoqiancode;
    }

    public void setBiaoqiancode(String biaoqiancode) {
        this.biaoqiancode = biaoqiancode;
    }

    public String getBangdingshijian() {
        return bangdingshijian;
    }

    public void setBangdingshijian(String bangdingshijian) {
        this.bangdingshijian = bangdingshijian;
    }

    public String getBeizhu() {
        return beizhu;
    }

    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }

}
