package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GDLX.
 */
public class gdlx {

    private Long gdlxcode;
    private String gdlxname;

    public gdlx() {
    }

    public gdlx(Long gdlxcode) {
        this.gdlxcode = gdlxcode;
    }

    public gdlx(Long gdlxcode, String gdlxname) {
        this.gdlxcode = gdlxcode;
        this.gdlxname = gdlxname;
    }

    public Long getGdlxcode() {
        return gdlxcode;
    }

    public void setGdlxcode(Long gdlxcode) {
        this.gdlxcode = gdlxcode;
    }

    public String getGdlxname() {
        return gdlxname;
    }

    public void setGdlxname(String gdlxname) {
        this.gdlxname = gdlxname;
    }

}
