package com.intelligent.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GUANXIAN.
*/
public class guanxianDao extends AbstractDao<guanxian, Long> {

    public static final String TABLENAME = "GUANXIAN";

    /**
     * Properties of entity guanxian.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Guanxiancode = new Property(0, Long.class, "guanxiancode", true, "GUANXIANCODE");
        public final static Property Guanxianleixing = new Property(1, String.class, "guanxianleixing", false, "GUANXIANLEIXING");
        public final static Property Guanxianqidianhao = new Property(2, String.class, "guanxianqidianhao", false, "GUANXIANQIDIANHAO");
        public final static Property Guanxianzhongdianhao = new Property(3, String.class, "guanxianzhongdianhao", false, "GUANXIANZHONGDIANHAO");
        public final static Property Guanxianqidianmaishen = new Property(4, String.class, "guanxianqidianmaishen", false, "GUANXIANQIDIANMAISHEN");
        public final static Property Guanxianzhongdianmaishen = new Property(5, String.class, "guanxianzhongdianmaishen", false, "GUANXIANZHONGDIANMAISHEN");
        public final static Property Duanmianzhicun = new Property(6, String.class, "duanmianzhicun", false, "DUANMIANZHICUN");
        public final static Property Jiemiandaxiao = new Property(7, String.class, "jiemiandaxiao", false, "JIEMIANDAXIAO");
        public final static Property Caizhi = new Property(8, String.class, "caizhi", false, "CAIZHI");
        public final static Property Maishefangshi = new Property(9, String.class, "maishefangshi", false, "MAISHEFANGSHI");
        public final static Property Zongkongshu = new Property(10, String.class, "zongkongshu", false, "ZONGKONGSHU");
        public final static Property Yiyongkongshu = new Property(11, String.class, "yiyongkongshu", false, "YIYONGKONGSHU");
        public final static Property Dianlantiaoshu = new Property(12, String.class, "dianlantiaoshu", false, "DIANLANTIAOSHU");
        public final static Property Dianyazhi = new Property(13, String.class, "dianyazhi", false, "DIANYAZHI");
        public final static Property Yalileixing = new Property(14, String.class, "yalileixing", false, "YALILEIXING");
        public final static Property Paishuiliuxiang = new Property(15, String.class, "paishuiliuxiang", false, "PAISHUILIUXIANG");
        public final static Property Baohucailiao = new Property(16, String.class, "baohucailiao", false, "BAOHUCAILIAO");
        public final static Property Puchaniandai = new Property(17, String.class, "puchaniandai", false, "PUCHANIANDAI");
        public final static Property Quanshudanwei = new Property(18, String.class, "quanshudanwei", false, "QUANSHUDANWEI");
        public final static Property Dimiangaocheng = new Property(19, String.class, "dimiangaocheng", false, "DIMIANGAOCHENG");
        public final static Property Guanxiandiangaocheng = new Property(20, String.class, "guanxiandiangaocheng", false, "GUANXIANDIANGAOCHENG");
        public final static Property Dianbeizhu = new Property(21, String.class, "dianbeizhu", false, "DIANBEIZHU");
        public final static Property Shifoujiebian = new Property(22, String.class, "shifoujiebian", false, "SHIFOUJIEBIAN");
        public final static Property Daolumingcheng = new Property(23, String.class, "daolumingcheng", false, "DAOLUMINGCHENG");
    };


    public guanxianDao(DaoConfig config) {
        super(config);
    }
    
    public guanxianDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GUANXIAN' (" + //
                "'GUANXIANCODE' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: guanxiancode
                "'GUANXIANLEIXING' TEXT," + // 1: guanxianleixing
                "'GUANXIANQIDIANHAO' TEXT," + // 2: guanxianqidianhao
                "'GUANXIANZHONGDIANHAO' TEXT," + // 3: guanxianzhongdianhao
                "'GUANXIANQIDIANMAISHEN' TEXT," + // 4: guanxianqidianmaishen
                "'GUANXIANZHONGDIANMAISHEN' TEXT," + // 5: guanxianzhongdianmaishen
                "'DUANMIANZHICUN' TEXT," + // 6: duanmianzhicun
                "'JIEMIANDAXIAO' TEXT," + // 7: jiemiandaxiao
                "'CAIZHI' TEXT," + // 8: caizhi
                "'MAISHEFANGSHI' TEXT," + // 9: maishefangshi
                "'ZONGKONGSHU' TEXT," + // 10: zongkongshu
                "'YIYONGKONGSHU' TEXT," + // 11: yiyongkongshu
                "'DIANLANTIAOSHU' TEXT," + // 12: dianlantiaoshu
                "'DIANYAZHI' TEXT," + // 13: dianyazhi
                "'YALILEIXING' TEXT," + // 14: yalileixing
                "'PAISHUILIUXIANG' TEXT," + // 15: paishuiliuxiang
                "'BAOHUCAILIAO' TEXT," + // 16: baohucailiao
                "'PUCHANIANDAI' TEXT," + // 17: puchaniandai
                "'QUANSHUDANWEI' TEXT," + // 18: quanshudanwei
                "'DIMIANGAOCHENG' TEXT," + // 19: dimiangaocheng
                "'GUANXIANDIANGAOCHENG' TEXT," + // 20: guanxiandiangaocheng
                "'DIANBEIZHU' TEXT," + // 21: dianbeizhu
                "'SHIFOUJIEBIAN' TEXT," + // 22: shifoujiebian
                "'DAOLUMINGCHENG' TEXT);"); // 23: daolumingcheng
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GUANXIAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, guanxian entity) {
        stmt.clearBindings();
 
        Long guanxiancode = entity.getGuanxiancode();
        if (guanxiancode != null) {
            stmt.bindLong(1, guanxiancode);
        }
 
        String guanxianleixing = entity.getGuanxianleixing();
        if (guanxianleixing != null) {
            stmt.bindString(2, guanxianleixing);
        }
 
        String guanxianqidianhao = entity.getGuanxianqidianhao();
        if (guanxianqidianhao != null) {
            stmt.bindString(3, guanxianqidianhao);
        }
 
        String guanxianzhongdianhao = entity.getGuanxianzhongdianhao();
        if (guanxianzhongdianhao != null) {
            stmt.bindString(4, guanxianzhongdianhao);
        }
 
        String guanxianqidianmaishen = entity.getGuanxianqidianmaishen();
        if (guanxianqidianmaishen != null) {
            stmt.bindString(5, guanxianqidianmaishen);
        }
 
        String guanxianzhongdianmaishen = entity.getGuanxianzhongdianmaishen();
        if (guanxianzhongdianmaishen != null) {
            stmt.bindString(6, guanxianzhongdianmaishen);
        }
 
        String duanmianzhicun = entity.getDuanmianzhicun();
        if (duanmianzhicun != null) {
            stmt.bindString(7, duanmianzhicun);
        }
 
        String jiemiandaxiao = entity.getJiemiandaxiao();
        if (jiemiandaxiao != null) {
            stmt.bindString(8, jiemiandaxiao);
        }
 
        String caizhi = entity.getCaizhi();
        if (caizhi != null) {
            stmt.bindString(9, caizhi);
        }
 
        String maishefangshi = entity.getMaishefangshi();
        if (maishefangshi != null) {
            stmt.bindString(10, maishefangshi);
        }
 
        String zongkongshu = entity.getZongkongshu();
        if (zongkongshu != null) {
            stmt.bindString(11, zongkongshu);
        }
 
        String yiyongkongshu = entity.getYiyongkongshu();
        if (yiyongkongshu != null) {
            stmt.bindString(12, yiyongkongshu);
        }
 
        String dianlantiaoshu = entity.getDianlantiaoshu();
        if (dianlantiaoshu != null) {
            stmt.bindString(13, dianlantiaoshu);
        }
 
        String dianyazhi = entity.getDianyazhi();
        if (dianyazhi != null) {
            stmt.bindString(14, dianyazhi);
        }
 
        String yalileixing = entity.getYalileixing();
        if (yalileixing != null) {
            stmt.bindString(15, yalileixing);
        }
 
        String paishuiliuxiang = entity.getPaishuiliuxiang();
        if (paishuiliuxiang != null) {
            stmt.bindString(16, paishuiliuxiang);
        }
 
        String baohucailiao = entity.getBaohucailiao();
        if (baohucailiao != null) {
            stmt.bindString(17, baohucailiao);
        }
 
        String puchaniandai = entity.getPuchaniandai();
        if (puchaniandai != null) {
            stmt.bindString(18, puchaniandai);
        }
 
        String quanshudanwei = entity.getQuanshudanwei();
        if (quanshudanwei != null) {
            stmt.bindString(19, quanshudanwei);
        }
 
        String dimiangaocheng = entity.getDimiangaocheng();
        if (dimiangaocheng != null) {
            stmt.bindString(20, dimiangaocheng);
        }
 
        String guanxiandiangaocheng = entity.getGuanxiandiangaocheng();
        if (guanxiandiangaocheng != null) {
            stmt.bindString(21, guanxiandiangaocheng);
        }
 
        String dianbeizhu = entity.getDianbeizhu();
        if (dianbeizhu != null) {
            stmt.bindString(22, dianbeizhu);
        }
 
        String shifoujiebian = entity.getShifoujiebian();
        if (shifoujiebian != null) {
            stmt.bindString(23, shifoujiebian);
        }
 
        String daolumingcheng = entity.getDaolumingcheng();
        if (daolumingcheng != null) {
            stmt.bindString(24, daolumingcheng);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public guanxian readEntity(Cursor cursor, int offset) {
        guanxian entity = new guanxian( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // guanxiancode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // guanxianleixing
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // guanxianqidianhao
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // guanxianzhongdianhao
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // guanxianqidianmaishen
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // guanxianzhongdianmaishen
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // duanmianzhicun
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // jiemiandaxiao
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // caizhi
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // maishefangshi
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // zongkongshu
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // yiyongkongshu
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // dianlantiaoshu
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // dianyazhi
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // yalileixing
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // paishuiliuxiang
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // baohucailiao
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // puchaniandai
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // quanshudanwei
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // dimiangaocheng
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // guanxiandiangaocheng
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // dianbeizhu
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // shifoujiebian
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23) // daolumingcheng
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, guanxian entity, int offset) {
        entity.setGuanxiancode(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGuanxianleixing(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGuanxianqidianhao(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGuanxianzhongdianhao(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGuanxianqidianmaishen(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGuanxianzhongdianmaishen(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDuanmianzhicun(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJiemiandaxiao(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCaizhi(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMaishefangshi(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setZongkongshu(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setYiyongkongshu(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDianlantiaoshu(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDianyazhi(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setYalileixing(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPaishuiliuxiang(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setBaohucailiao(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPuchaniandai(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setQuanshudanwei(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDimiangaocheng(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setGuanxiandiangaocheng(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDianbeizhu(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setShifoujiebian(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDaolumingcheng(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(guanxian entity, long rowId) {
        entity.setGuanxiancode(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(guanxian entity) {
        if(entity != null) {
            return entity.getGuanxiancode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
