package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GUANDIAN.
 */
public class guandian {

    private Long guandiancode;
    private String guanlei;
    private String guanxianqidianhao;
    private String tezheng;
    private String fushuwu;
    private String dianleixing;
    private String jingleixing;
    private String daolumingcheng;
    private String jingdu;
    private String weidu;
    private String dimiangaocheng;
    private String guandiangaocheng;
    private String biaoqiancode;
    private String bangdingshijian;
    private String beizhu;

    public guandian() {
    }

    public guandian(Long guandiancode) {
        this.guandiancode = guandiancode;
    }

    public guandian(Long guandiancode, String guanlei, String guanxianqidianhao, String tezheng, String fushuwu, String dianleixing, String jingleixing, String daolumingcheng, String jingdu, String weidu, String dimiangaocheng, String guandiangaocheng, String biaoqiancode, String bangdingshijian, String beizhu) {
        this.guandiancode = guandiancode;
        this.guanlei = guanlei;
        this.guanxianqidianhao = guanxianqidianhao;
        this.tezheng = tezheng;
        this.fushuwu = fushuwu;
        this.dianleixing = dianleixing;
        this.jingleixing = jingleixing;
        this.daolumingcheng = daolumingcheng;
        this.jingdu = jingdu;
        this.weidu = weidu;
        this.dimiangaocheng = dimiangaocheng;
        this.guandiangaocheng = guandiangaocheng;
        this.biaoqiancode = biaoqiancode;
        this.bangdingshijian = bangdingshijian;
        this.beizhu = beizhu;
    }

    public Long getGuandiancode() {
        return guandiancode;
    }

    public void setGuandiancode(Long guandiancode) {
        this.guandiancode = guandiancode;
    }

    public String getGuanlei() {
        return guanlei;
    }

    public void setGuanlei(String guanlei) {
        this.guanlei = guanlei;
    }

    public String getGuanxianqidianhao() {
        return guanxianqidianhao;
    }

    public void setGuanxianqidianhao(String guanxianqidianhao) {
        this.guanxianqidianhao = guanxianqidianhao;
    }

    public String getTezheng() {
        return tezheng;
    }

    public void setTezheng(String tezheng) {
        this.tezheng = tezheng;
    }

    public String getFushuwu() {
        return fushuwu;
    }

    public void setFushuwu(String fushuwu) {
        this.fushuwu = fushuwu;
    }

    public String getDianleixing() {
        return dianleixing;
    }

    public void setDianleixing(String dianleixing) {
        this.dianleixing = dianleixing;
    }

    public String getJingleixing() {
        return jingleixing;
    }

    public void setJingleixing(String jingleixing) {
        this.jingleixing = jingleixing;
    }

    public String getDaolumingcheng() {
        return daolumingcheng;
    }

    public void setDaolumingcheng(String daolumingcheng) {
        this.daolumingcheng = daolumingcheng;
    }

    public String getJingdu() {
        return jingdu;
    }

    public void setJingdu(String jingdu) {
        this.jingdu = jingdu;
    }

    public String getWeidu() {
        return weidu;
    }

    public void setWeidu(String weidu) {
        this.weidu = weidu;
    }

    public String getDimiangaocheng() {
        return dimiangaocheng;
    }

    public void setDimiangaocheng(String dimiangaocheng) {
        this.dimiangaocheng = dimiangaocheng;
    }

    public String getGuandiangaocheng() {
        return guandiangaocheng;
    }

    public void setGuandiangaocheng(String guandiangaocheng) {
        this.guandiangaocheng = guandiangaocheng;
    }

    public String getBiaoqiancode() {
        return biaoqiancode;
    }

    public void setBiaoqiancode(String biaoqiancode) {
        this.biaoqiancode = biaoqiancode;
    }

    public String getBangdingshijian() {
        return bangdingshijian;
    }

    public void setBangdingshijian(String bangdingshijian) {
        this.bangdingshijian = bangdingshijian;
    }

    public String getBeizhu() {
        return beizhu;
    }

    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }

}
