package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GUANXIAN.
 */
public class guanxian {

    private Long guanxiancode;
    private String guanxianleixing;
    private String guanxianqidianhao;
    private String guanxianzhongdianhao;
    private String guanxianqidianmaishen;
    private String guanxianzhongdianmaishen;
    private String duanmianzhicun;
    private String jiemiandaxiao;
    private String caizhi;
    private String maishefangshi;
    private String zongkongshu;
    private String yiyongkongshu;
    private String dianlantiaoshu;
    private String dianyazhi;
    private String yalileixing;
    private String paishuiliuxiang;
    private String baohucailiao;
    private String puchaniandai;
    private String quanshudanwei;
    private String dimiangaocheng;
    private String guanxiandiangaocheng;
    private String dianbeizhu;
    private String shifoujiebian;
    private String daolumingcheng;

    public guanxian() {
    }

    public guanxian(Long guanxiancode) {
        this.guanxiancode = guanxiancode;
    }

    public guanxian(Long guanxiancode, String guanxianleixing, String guanxianqidianhao, String guanxianzhongdianhao, String guanxianqidianmaishen, String guanxianzhongdianmaishen, String duanmianzhicun, String jiemiandaxiao, String caizhi, String maishefangshi, String zongkongshu, String yiyongkongshu, String dianlantiaoshu, String dianyazhi, String yalileixing, String paishuiliuxiang, String baohucailiao, String puchaniandai, String quanshudanwei, String dimiangaocheng, String guanxiandiangaocheng, String dianbeizhu, String shifoujiebian, String daolumingcheng) {
        this.guanxiancode = guanxiancode;
        this.guanxianleixing = guanxianleixing;
        this.guanxianqidianhao = guanxianqidianhao;
        this.guanxianzhongdianhao = guanxianzhongdianhao;
        this.guanxianqidianmaishen = guanxianqidianmaishen;
        this.guanxianzhongdianmaishen = guanxianzhongdianmaishen;
        this.duanmianzhicun = duanmianzhicun;
        this.jiemiandaxiao = jiemiandaxiao;
        this.caizhi = caizhi;
        this.maishefangshi = maishefangshi;
        this.zongkongshu = zongkongshu;
        this.yiyongkongshu = yiyongkongshu;
        this.dianlantiaoshu = dianlantiaoshu;
        this.dianyazhi = dianyazhi;
        this.yalileixing = yalileixing;
        this.paishuiliuxiang = paishuiliuxiang;
        this.baohucailiao = baohucailiao;
        this.puchaniandai = puchaniandai;
        this.quanshudanwei = quanshudanwei;
        this.dimiangaocheng = dimiangaocheng;
        this.guanxiandiangaocheng = guanxiandiangaocheng;
        this.dianbeizhu = dianbeizhu;
        this.shifoujiebian = shifoujiebian;
        this.daolumingcheng = daolumingcheng;
    }

    public Long getGuanxiancode() {
        return guanxiancode;
    }

    public void setGuanxiancode(Long guanxiancode) {
        this.guanxiancode = guanxiancode;
    }

    public String getGuanxianleixing() {
        return guanxianleixing;
    }

    public void setGuanxianleixing(String guanxianleixing) {
        this.guanxianleixing = guanxianleixing;
    }

    public String getGuanxianqidianhao() {
        return guanxianqidianhao;
    }

    public void setGuanxianqidianhao(String guanxianqidianhao) {
        this.guanxianqidianhao = guanxianqidianhao;
    }

    public String getGuanxianzhongdianhao() {
        return guanxianzhongdianhao;
    }

    public void setGuanxianzhongdianhao(String guanxianzhongdianhao) {
        this.guanxianzhongdianhao = guanxianzhongdianhao;
    }

    public String getGuanxianqidianmaishen() {
        return guanxianqidianmaishen;
    }

    public void setGuanxianqidianmaishen(String guanxianqidianmaishen) {
        this.guanxianqidianmaishen = guanxianqidianmaishen;
    }

    public String getGuanxianzhongdianmaishen() {
        return guanxianzhongdianmaishen;
    }

    public void setGuanxianzhongdianmaishen(String guanxianzhongdianmaishen) {
        this.guanxianzhongdianmaishen = guanxianzhongdianmaishen;
    }

    public String getDuanmianzhicun() {
        return duanmianzhicun;
    }

    public void setDuanmianzhicun(String duanmianzhicun) {
        this.duanmianzhicun = duanmianzhicun;
    }

    public String getJiemiandaxiao() {
        return jiemiandaxiao;
    }

    public void setJiemiandaxiao(String jiemiandaxiao) {
        this.jiemiandaxiao = jiemiandaxiao;
    }

    public String getCaizhi() {
        return caizhi;
    }

    public void setCaizhi(String caizhi) {
        this.caizhi = caizhi;
    }

    public String getMaishefangshi() {
        return maishefangshi;
    }

    public void setMaishefangshi(String maishefangshi) {
        this.maishefangshi = maishefangshi;
    }

    public String getZongkongshu() {
        return zongkongshu;
    }

    public void setZongkongshu(String zongkongshu) {
        this.zongkongshu = zongkongshu;
    }

    public String getYiyongkongshu() {
        return yiyongkongshu;
    }

    public void setYiyongkongshu(String yiyongkongshu) {
        this.yiyongkongshu = yiyongkongshu;
    }

    public String getDianlantiaoshu() {
        return dianlantiaoshu;
    }

    public void setDianlantiaoshu(String dianlantiaoshu) {
        this.dianlantiaoshu = dianlantiaoshu;
    }

    public String getDianyazhi() {
        return dianyazhi;
    }

    public void setDianyazhi(String dianyazhi) {
        this.dianyazhi = dianyazhi;
    }

    public String getYalileixing() {
        return yalileixing;
    }

    public void setYalileixing(String yalileixing) {
        this.yalileixing = yalileixing;
    }

    public String getPaishuiliuxiang() {
        return paishuiliuxiang;
    }

    public void setPaishuiliuxiang(String paishuiliuxiang) {
        this.paishuiliuxiang = paishuiliuxiang;
    }

    public String getBaohucailiao() {
        return baohucailiao;
    }

    public void setBaohucailiao(String baohucailiao) {
        this.baohucailiao = baohucailiao;
    }

    public String getPuchaniandai() {
        return puchaniandai;
    }

    public void setPuchaniandai(String puchaniandai) {
        this.puchaniandai = puchaniandai;
    }

    public String getQuanshudanwei() {
        return quanshudanwei;
    }

    public void setQuanshudanwei(String quanshudanwei) {
        this.quanshudanwei = quanshudanwei;
    }

    public String getDimiangaocheng() {
        return dimiangaocheng;
    }

    public void setDimiangaocheng(String dimiangaocheng) {
        this.dimiangaocheng = dimiangaocheng;
    }

    public String getGuanxiandiangaocheng() {
        return guanxiandiangaocheng;
    }

    public void setGuanxiandiangaocheng(String guanxiandiangaocheng) {
        this.guanxiandiangaocheng = guanxiandiangaocheng;
    }

    public String getDianbeizhu() {
        return dianbeizhu;
    }

    public void setDianbeizhu(String dianbeizhu) {
        this.dianbeizhu = dianbeizhu;
    }

    public String getShifoujiebian() {
        return shifoujiebian;
    }

    public void setShifoujiebian(String shifoujiebian) {
        this.shifoujiebian = shifoujiebian;
    }

    public String getDaolumingcheng() {
        return daolumingcheng;
    }

    public void setDaolumingcheng(String daolumingcheng) {
        this.daolumingcheng = daolumingcheng;
    }

}
