package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GUZHANGSHENBAO.
 */
public class guzhangshenbao {

    private Long shenbaoid;
    private String shenbaorenyuan;
    private String shenbaoriqi;
    private String guzhangleixing;
    private String guzhangshuoming;
    private String jingdu;
    private String weidu;
    private String shenbaobiaoqianid;
    private String zhaopianurl;

    public guzhangshenbao() {
    }

    public guzhangshenbao(Long shenbaoid) {
        this.shenbaoid = shenbaoid;
    }

    public guzhangshenbao(Long shenbaoid, String shenbaorenyuan, String shenbaoriqi, String guzhangleixing, String guzhangshuoming, String jingdu, String weidu, String shenbaobiaoqianid, String zhaopianurl) {
        this.shenbaoid = shenbaoid;
        this.shenbaorenyuan = shenbaorenyuan;
        this.shenbaoriqi = shenbaoriqi;
        this.guzhangleixing = guzhangleixing;
        this.guzhangshuoming = guzhangshuoming;
        this.jingdu = jingdu;
        this.weidu = weidu;
        this.shenbaobiaoqianid = shenbaobiaoqianid;
        this.zhaopianurl = zhaopianurl;
    }

    public Long getShenbaoid() {
        return shenbaoid;
    }

    public void setShenbaoid(Long shenbaoid) {
        this.shenbaoid = shenbaoid;
    }

    public String getShenbaorenyuan() {
        return shenbaorenyuan;
    }

    public void setShenbaorenyuan(String shenbaorenyuan) {
        this.shenbaorenyuan = shenbaorenyuan;
    }

    public String getShenbaoriqi() {
        return shenbaoriqi;
    }

    public void setShenbaoriqi(String shenbaoriqi) {
        this.shenbaoriqi = shenbaoriqi;
    }

    public String getGuzhangleixing() {
        return guzhangleixing;
    }

    public void setGuzhangleixing(String guzhangleixing) {
        this.guzhangleixing = guzhangleixing;
    }

    public String getGuzhangshuoming() {
        return guzhangshuoming;
    }

    public void setGuzhangshuoming(String guzhangshuoming) {
        this.guzhangshuoming = guzhangshuoming;
    }

    public String getJingdu() {
        return jingdu;
    }

    public void setJingdu(String jingdu) {
        this.jingdu = jingdu;
    }

    public String getWeidu() {
        return weidu;
    }

    public void setWeidu(String weidu) {
        this.weidu = weidu;
    }

    public String getShenbaobiaoqianid() {
        return shenbaobiaoqianid;
    }

    public void setShenbaobiaoqianid(String shenbaobiaoqianid) {
        this.shenbaobiaoqianid = shenbaobiaoqianid;
    }

    public String getZhaopianurl() {
        return zhaopianurl;
    }

    public void setZhaopianurl(String zhaopianurl) {
        this.zhaopianurl = zhaopianurl;
    }

}
