package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GXLB.
 */
public class gxlb {

    private Long gxlbcode;
    private String gxlbname;

    public gxlb() {
    }

    public gxlb(Long gxlbcode) {
        this.gxlbcode = gxlbcode;
    }

    public gxlb(Long gxlbcode, String gxlbname) {
        this.gxlbcode = gxlbcode;
        this.gxlbname = gxlbname;
    }

    public Long getGxlbcode() {
        return gxlbcode;
    }

    public void setGxlbcode(Long gxlbcode) {
        this.gxlbcode = gxlbcode;
    }

    public String getGxlbname() {
        return gxlbname;
    }

    public void setGxlbname(String gxlbname) {
        this.gxlbname = gxlbname;
    }

}
