package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JLX.
 */
public class jlx {

    private Long jlxcode;
    private String jlxname;

    public jlx() {
    }

    public jlx(Long jlxcode) {
        this.jlxcode = jlxcode;
    }

    public jlx(Long jlxcode, String jlxname) {
        this.jlxcode = jlxcode;
        this.jlxname = jlxname;
    }

    public Long getJlxcode() {
        return jlxcode;
    }

    public void setJlxcode(Long jlxcode) {
        this.jlxcode = jlxcode;
    }

    public String getJlxname() {
        return jlxname;
    }

    public void setJlxname(String jlxname) {
        this.jlxname = jlxname;
    }

}
