package com.intelligent.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table JLX.
*/
public class jlxDao extends AbstractDao<jlx, Long> {

    public static final String TABLENAME = "JLX";

    /**
     * Properties of entity jlx.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Jlxcode = new Property(0, Long.class, "jlxcode", true, "JLXCODE");
        public final static Property Jlxname = new Property(1, String.class, "jlxname", false, "JLXNAME");
    };


    public jlxDao(DaoConfig config) {
        super(config);
    }
    
    public jlxDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'JLX' (" + //
                "'JLXCODE' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: jlxcode
                "'JLXNAME' TEXT);"); // 1: jlxname
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'JLX'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, jlx entity) {
        stmt.clearBindings();
 
        Long jlxcode = entity.getJlxcode();
        if (jlxcode != null) {
            stmt.bindLong(1, jlxcode);
        }
 
        String jlxname = entity.getJlxname();
        if (jlxname != null) {
            stmt.bindString(2, jlxname);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public jlx readEntity(Cursor cursor, int offset) {
        jlx entity = new jlx( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // jlxcode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // jlxname
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, jlx entity, int offset) {
        entity.setJlxcode(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJlxname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(jlx entity, long rowId) {
        entity.setJlxcode(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(jlx entity) {
        if(entity != null) {
            return entity.getJlxcode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
