package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHUXING.
 */
public class shuxing {

    private Long shuxingcode;
    private String shuxingname;
    private String shuxingziduan;

    public shuxing() {
    }

    public shuxing(Long shuxingcode) {
        this.shuxingcode = shuxingcode;
    }

    public shuxing(Long shuxingcode, String shuxingname, String shuxingziduan) {
        this.shuxingcode = shuxingcode;
        this.shuxingname = shuxingname;
        this.shuxingziduan = shuxingziduan;
    }

    public Long getShuxingcode() {
        return shuxingcode;
    }

    public void setShuxingcode(Long shuxingcode) {
        this.shuxingcode = shuxingcode;
    }

    public String getShuxingname() {
        return shuxingname;
    }

    public void setShuxingname(String shuxingname) {
        this.shuxingname = shuxingname;
    }

    public String getShuxingziduan() {
        return shuxingziduan;
    }

    public void setShuxingziduan(String shuxingziduan) {
        this.shuxingziduan = shuxingziduan;
    }

}
