package com.intelligent.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table XUNCHA.
 */
public class xuncha {

    private Long xunchaid;
    private String xuncharenyuan;
    private String xunchariqi;
    private String xunchaqingkuang;
    private String chuliqingkuang;
    private String jingdu;
    private String weidu;
    private String xunchabiaoqianid;
    private String zhaopianurl;

    public xuncha() {
    }

    public xuncha(Long xunchaid) {
        this.xunchaid = xunchaid;
    }

    public xuncha(Long xunchaid, String xuncharenyuan, String xunchariqi, String xunchaqingkuang, String chuliqingkuang, String jingdu, String weidu, String xunchabiaoqianid, String zhaopianurl) {
        this.xunchaid = xunchaid;
        this.xuncharenyuan = xuncharenyuan;
        this.xunchariqi = xunchariqi;
        this.xunchaqingkuang = xunchaqingkuang;
        this.chuliqingkuang = chuliqingkuang;
        this.jingdu = jingdu;
        this.weidu = weidu;
        this.xunchabiaoqianid = xunchabiaoqianid;
        this.zhaopianurl = zhaopianurl;
    }

    public Long getXunchaid() {
        return xunchaid;
    }

    public void setXunchaid(Long xunchaid) {
        this.xunchaid = xunchaid;
    }

    public String getXuncharenyuan() {
        return xuncharenyuan;
    }

    public void setXuncharenyuan(String xuncharenyuan) {
        this.xuncharenyuan = xuncharenyuan;
    }

    public String getXunchariqi() {
        return xunchariqi;
    }

    public void setXunchariqi(String xunchariqi) {
        this.xunchariqi = xunchariqi;
    }

    public String getXunchaqingkuang() {
        return xunchaqingkuang;
    }

    public void setXunchaqingkuang(String xunchaqingkuang) {
        this.xunchaqingkuang = xunchaqingkuang;
    }

    public String getChuliqingkuang() {
        return chuliqingkuang;
    }

    public void setChuliqingkuang(String chuliqingkuang) {
        this.chuliqingkuang = chuliqingkuang;
    }

    public String getJingdu() {
        return jingdu;
    }

    public void setJingdu(String jingdu) {
        this.jingdu = jingdu;
    }

    public String getWeidu() {
        return weidu;
    }

    public void setWeidu(String weidu) {
        this.weidu = weidu;
    }

    public String getXunchabiaoqianid() {
        return xunchabiaoqianid;
    }

    public void setXunchabiaoqianid(String xunchabiaoqianid) {
        this.xunchabiaoqianid = xunchabiaoqianid;
    }

    public String getZhaopianurl() {
        return zhaopianurl;
    }

    public void setZhaopianurl(String zhaopianurl) {
        this.zhaopianurl = zhaopianurl;
    }

}
